-- 1. Add GSTIN column to stores table
ALTER TABLE stores 
ADD COLUMN IF NOT EXISTS gstin VARCHAR(20) DEFAULT NULL;

-- 2. Add HSN code and GST rate columns to products table
ALTER TABLE products 
ADD COLUMN IF NOT EXISTS hsn_code VARCHAR(20) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS gst_rate NUMERIC(5,2) NOT NULL DEFAULT 12.00;

-- 3. Add GST tracking columns to order_items table
ALTER TABLE order_items 
ADD COLUMN IF NOT EXISTS hsn_code VARCHAR(20) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS gst_rate NUMERIC(5,2) NOT NULL DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS taxable_value NUMERIC(10,2) NOT NULL DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS cgst_amount NUMERIC(10,2) NOT NULL DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS sgst_amount NUMERIC(10,2) NOT NULL DEFAULT 0.00;

-- 4. Add GST summary columns to orders table
ALTER TABLE orders 
ADD COLUMN IF NOT EXISTS is_gst_bill BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS total_taxable_value NUMERIC(10,2) NOT NULL DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS total_cgst NUMERIC(10,2) NOT NULL DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS total_sgst NUMERIC(10,2) NOT NULL DEFAULT 0.00;
